./csim -S 8 -K 1 -B 1 -p LRU -t traces/simple_direct.trace
./csim -S 4 -K 1 -B 1 -p LRU -t traces/simple_direct.trace
./csim -S 2 -K 1 -B 1 -p LRU -t traces/simple_direct.trace
./csim -S 1 -K 1 -B 4 -p LRU -t traces/simple_direct.trace
./csim -S 2 -K 1 -B 4 -p LRU -t traces/simple_direct.trace
./csim -S 1 -K 1 -B 8 -p LRU -t traces/simple_direct.trace
./csim -S 4 -K 1 -B 2 -p LRU -t traces/simple_direct.trace
./csim -S 2 -K 1 -B 2 -p LRU -t traces/simple_direct.trace
./csim -S 2 -K 1 -B 2 -p LRU -t traces/yi2.trace
./csim -S 4 -K 1 -B 16 -p LRU -t traces/dave.trace
./csim -S 4 -K 1 -B 8 -p LRU -t traces/trans.trace
./csim -S 32 -K 1 -B 32 -p LRU -t traces/trans.trace
./csim -S 32 -K 1 -B 32 -p LRU -t traces/long.trace
./csim -S 8 -K 1 -B 1 -p FIFO -t traces/simple_direct.trace
./csim -S 4 -K 1 -B 1 -p FIFO -t traces/simple_direct.trace
./csim -S 2 -K 1 -B 1 -p FIFO -t traces/simple_direct.trace
./csim -S 1 -K 1 -B 4 -p FIFO -t traces/simple_direct.trace
./csim -S 2 -K 1 -B 4 -p FIFO -t traces/simple_direct.trace
./csim -S 1 -K 1 -B 8 -p FIFO -t traces/simple_direct.trace
./csim -S 4 -K 1 -B 2 -p FIFO -t traces/simple_direct.trace
./csim -S 2 -K 1 -B 2 -p FIFO -t traces/simple_direct.trace
./csim -S 2 -K 1 -B 2 -p FIFO -t traces/yi2.trace
./csim -S 4 -K 1 -B 16 -p FIFO -t traces/dave.trace
./csim -S 4 -K 1 -B 8 -p FIFO -t traces/trans.trace
./csim -S 32 -K 1 -B 32 -p FIFO -t traces/trans.trace
./csim -S 32 -K 1 -B 32 -p FIFO -t traces/long.trace
