./csim -S 2 -K 2 -B 2 -p LRU -t traces/simple_policy.trace
./csim -S 2 -K 2 -B 2 -p FIFO -t traces/simple_policy.trace
./csim -S 2 -K 2 -B 1 -p LRU -t traces/simple_policy.trace
./csim -S 2 -K 2 -B 1 -p FIFO -t traces/simple_policy.trace
./csim -S 16 -K 2 -B 16 -p LRU -t traces/yi.trace
./csim -S 4 -K 2 -B 8 -p LRU -t traces/trans_1.trace
./csim -S 4 -K 4 -B 8 -p LRU -t traces/trans_1.trace
./csim -S 16 -K 2 -B 16 -p LRU -t traces/fifo_s1.trace
./csim -S 16 -K 2 -B 16 -p LRU -t traces/fifo_s2.trace
./csim -S 16 -K 4 -B 16 -p LRU -t traces/fifo_s3.trace
./csim -S 32 -K 2 -B 4 -p LRU -t traces/fifo_m1_1.trace
./csim -S 8 -K 4 -B 4 -p LRU -t traces/fifo_m1_1.trace
./csim -S 32 -K 2 -B 4 -p LRU -t traces/fifo_m2_1.trace
./csim -S 8 -K 4 -B 4 -p LRU -t traces/fifo_m2_1.trace
./csim -S 16 -K 2 -B 16 -p LRU -t traces/fifo_l_1.trace
./csim -S 16 -K 2 -B 16 -p FIFO -t traces/yi.trace
./csim -S 4 -K 2 -B 8 -p FIFO -t traces/trans_1.trace
./csim -S 4 -K 4 -B 8 -p FIFO -t traces/trans_1.trace
./csim -S 16 -K 2 -B 16 -p FIFO -t traces/fifo_s1.trace
./csim -S 16 -K 2 -B 16 -p FIFO -t traces/fifo_s2.trace
./csim -S 16 -K 4 -B 16 -p FIFO -t traces/fifo_s3.trace
./csim -S 32 -K 2 -B 4 -p FIFO -t traces/fifo_m1_1.trace
./csim -S 8 -K 4 -B 4 -p FIFO -t traces/fifo_m1_1.trace
./csim -S 32 -K 2 -B 4 -p FIFO -t traces/fifo_m2_1.trace
./csim -S 8 -K 4 -B 4 -p FIFO -t traces/fifo_m2_1.trace
./csim -S 16 -K 2 -B 16 -p FIFO -t traces/fifo_l_1.trace
