./csim -S 1 -K 1 -B 2 -p LRU -t traces/simple_size.trace
./csim -S 1 -K 1 -B 4 -p LRU -t traces/simple_size.trace
./csim -S 1 -K 1 -B 8 -p LRU -t traces/simple_size.trace
./csim -S 1 -K 2 -B 2 -p LRU -t traces/simple_size.trace
./csim -S 1 -K 2 -B 4 -p LRU -t traces/simple_size.trace
./csim -S 1 -K 2 -B 8 -p LRU -t traces/simple_size.trace
./csim -S 2 -K 1 -B 2 -p LRU -t traces/simple_size.trace
./csim -S 2 -K 1 -B 4 -p LRU -t traces/simple_size.trace
./csim -S 2 -K 1 -B 8 -p LRU -t traces/simple_size.trace
./csim -S 2 -K 2 -B 2 -p LRU -t traces/simple_size.trace
./csim -S 2 -K 3 -B 2 -p LRU -t traces/simple_size.trace
./csim -S 2 -K 4 -B 2 -p FIFO -t traces/simple_size.trace
./csim -S 1 -K 1 -B 2 -p FIFO -t traces/simple_size.trace
./csim -S 1 -K 1 -B 4 -p FIFO -t traces/simple_size.trace
./csim -S 1 -K 1 -B 8 -p FIFO -t traces/simple_size.trace
./csim -S 1 -K 2 -B 2 -p FIFO -t traces/simple_size.trace
./csim -S 1 -K 2 -B 4 -p FIFO -t traces/simple_size.trace
./csim -S 1 -K 2 -B 8 -p FIFO -t traces/simple_size.trace
./csim -S 2 -K 1 -B 2 -p FIFO -t traces/simple_size.trace
./csim -S 2 -K 1 -B 4 -p FIFO -t traces/simple_size.trace
./csim -S 2 -K 1 -B 8 -p FIFO -t traces/simple_size.trace
./csim -S 2 -K 2 -B 2 -p FIFO -t traces/simple_size.trace
./csim -S 2 -K 3 -B 2 -p FIFO -t traces/simple_size.trace
./csim -S 2 -K 4 -B 2 -p FIFO -t traces/simple_size.trace
./csim -S 32 -K 2 -B 4 -p LRU -t traces/simple_size2.trace
./csim -S 32 -K 2 -B 4 -p LRU -t traces/fifo_m1.trace
./csim -S 8 -K 4 -B 4 -p LRU -t traces/fifo_m1.trace
./csim -S 32 -K 2 -B 4 -p LRU -t traces/fifo_m2.trace
./csim -S 8 -K 4 -B 4 -p LRU -t traces/fifo_m2.trace
./csim -S 16 -K 2 -B 16 -p LRU -t traces/fifo_l.trace
./csim -S 32 -K 2 -B 4 -p FIFO -t traces/fifo_m1.trace
./csim -S 8 -K 4 -B 4 -p FIFO -t traces/fifo_m1.trace
./csim -S 32 -K 2 -B 4 -p FIFO -t traces/fifo_m2.trace
./csim -S 8 -K 4 -B 4 -p FIFO -t traces/fifo_m2.trace
./csim -S 16 -K 2 -B 16 -p FIFO -t traces/fifo_l.trace
